version = 1

test_patterns = ["/src/tests.test_unit.py"]

exclude_patterns = [
    "/dissertation/",
    "/data/",
    "/status_report/",
    "/presentation/"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
