name: Package MacOS application with PyInstaller
on:
  workflow_dispatch:

  pull_request:
    branches:
      - master
    paths:
      - "src/**"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          ls ~
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install pyinstaller
          pip install pymzml
          pip install -r src/requirements.txt

      - name: Build Executable
        run: |
          cd src/
          pyinstaller -D --windowed main.spec
          cd dist
          ls -la

      - uses: actions/upload-artifact@v2
        with:
          name: application
          path: src/dist/main.app
