# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Package Windows application with PyInstaller
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "src/**"

  pull_request:
    branches:
      - master
    paths:
      - "src/**"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install pyinstaller
          pip install pymzml
          pip install -r src/requirements.txt
          ls -r ../..
      - name: Build Executable
        run: |
          cd src/
          pyinstaller -D --add-data "assets/styles.css;assets/" --add-data "assets/positive.csv;assets/" --add-data "assets/negative.csv;assets/" main.py
      - uses: actions/upload-artifact@v2
        with:
          name: main-executable
          path: src/dist/main
